/* ------------------------------------------------------------------ */
/*  Kingsen community-sets API                                          */
/*  Express + better-sqlite3. Single file, no build step.               */
/*                                                                      */
/*  Endpoints (all JSON):                                               */
/*    GET  /health                  -> { ok: true }                     */
/*    GET  /sets?q=&lang=&sort=      -> [ set, ... ]                     */
/*    GET  /sets/:id                 -> set                             */
/*    POST /sets                     -> set     (publish)               */
/*    POST /sets/:id/like            -> { liked, likes }                */
/*    POST /sets/:id/use             -> { uses }                        */
/*    POST /sets/:id/report          -> { ok }                          */
/*                                                                      */
/*  Client identity comes from the X-Client-Id header (anonymous,       */
/*  generated by the app). Used to make likes idempotent + rate-limit.  */
/* ------------------------------------------------------------------ */
import express from "express";
import cors from "cors";
import rateLimit from "express-rate-limit";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createServer } from "node:http";
import { WebSocketServer } from "ws";
import { openDatabase } from "./db.js";
import { roomEngine } from "./rooms.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const PORT = process.env.PORT || 8787;
const DB_PATH = process.env.KINGSEN_DB || join(__dirname, "kingsen.db");
// comma-separated allowlist, e.g. "https://kingsen.app,https://www.kingsen.app"
// default "*" is fine for a public read/write gallery, but lock down for prod.
const ORIGINS = (process.env.KINGSEN_ORIGINS || "*").split(",").map((s) => s.trim());

const MAX_CODE_LEN = 4000;   // a KGS1 code; generous but bounded
const MAX_NAME_LEN = 40;
const MAX_AUTHOR_LEN = 24;

/* ---- db (better-sqlite3 if present, else built-in node:sqlite) ---- */
const { db, engine } = await openDatabase(DB_PATH);
db.exec(`
  CREATE TABLE IF NOT EXISTS sets (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    author     TEXT NOT NULL,
    lang       TEXT NOT NULL DEFAULT 'nl',
    code       TEXT NOT NULL,
    uses       INTEGER NOT NULL DEFAULT 0,
    likes      INTEGER NOT NULL DEFAULT 0,
    reports    INTEGER NOT NULL DEFAULT 0,
    hidden     INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    client_id  TEXT
  );
  CREATE TABLE IF NOT EXISTS likes (
    set_id    TEXT NOT NULL,
    client_id TEXT NOT NULL,
    PRIMARY KEY (set_id, client_id)
  );
  CREATE TABLE IF NOT EXISTS reports (
    set_id    TEXT NOT NULL,
    client_id TEXT NOT NULL,
    PRIMARY KEY (set_id, client_id)
  );
  CREATE INDEX IF NOT EXISTS idx_sets_uses  ON sets (uses DESC);
  CREATE INDEX IF NOT EXISTS idx_sets_likes ON sets (likes DESC);
  CREATE INDEX IF NOT EXISTS idx_sets_new   ON sets (created_at DESC);
`);

// Auto-seed the example sets on first boot (empty table), unless disabled.
if (process.env.KINGSEN_NO_SEED !== "1") {
  try {
    const count = db.prepare("SELECT COUNT(*) AS n FROM sets").get().n;
    if (Number(count) === 0) {
      const { seedInto } = await import("./seedData.js");
      const n = seedInto(db);
      console.log(`Seeded ${n} example set(s) on first boot.`);
    }
  } catch (e) {
    console.warn("Auto-seed skipped:", e.message);
  }
}

/* ---- helpers ---- */
const newId = () => "s_" + Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4);
const clientOf = (req) => String(req.get("X-Client-Id") || req.ip || "anon").slice(0, 64);
function clean(str, max) {
  return String(str == null ? "" : str).replace(/[\u0000-\u001f\u007f]/g, "").trim().slice(0, max);
}
function rowToPublic(row, liked) {
  return {
    id: row.id, name: row.name, author: row.author, lang: row.lang,
    code: row.code, uses: row.uses, likes: row.likes,
    createdAt: row.created_at, liked: !!liked,
  };
}

/* ---- app ---- */
const app = express();
app.set("trust proxy", 1); // behind nginx/caddy
app.use(express.json({ limit: "16kb" }));
app.use(cors({
  origin: ORIGINS.includes("*") ? true : ORIGINS,
  methods: ["GET", "POST"],
  allowedHeaders: ["Content-Type", "X-Client-Id"],
}));

const writeLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 20,                       // 20 writes/min per IP
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many requests, slow down." },
});
const publishLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 30,                       // 30 publishes/hour per IP
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Publish limit reached, try again later." },
});

app.get("/health", (_req, res) => res.json({ ok: true, engine }));

/* GET /sets */
app.get("/sets", (req, res) => {
  const sort = req.query.sort === "new" ? "created_at DESC"
    : req.query.sort === "likes" ? "likes DESC, uses DESC"
    : "uses DESC, likes DESC";
  const lang = clean(req.query.lang, 5);
  const q = clean(req.query.q, 60).toLowerCase();
  let sql = "SELECT * FROM sets WHERE hidden = 0";
  const params = [];
  if (lang === "nl" || lang === "en") { sql += " AND lang = ?"; params.push(lang); }
  if (q) { sql += " AND (lower(name) LIKE ? OR lower(author) LIKE ?)"; params.push("%" + q + "%", "%" + q + "%"); }
  sql += ` ORDER BY ${sort} LIMIT 100`;
  const rows = db.prepare(sql).all(...params);
  const cid = clientOf(req);
  const likedSet = new Set(
    db.prepare("SELECT set_id FROM likes WHERE client_id = ?").all(cid).map((r) => r.set_id)
  );
  res.json(rows.map((r) => rowToPublic(r, likedSet.has(r.id))));
});

/* GET /sets/:id */
app.get("/sets/:id", (req, res) => {
  const row = db.prepare("SELECT * FROM sets WHERE id = ? AND hidden = 0").get(req.params.id);
  if (!row) return res.status(404).json({ error: "Not found" });
  const liked = !!db.prepare("SELECT 1 FROM likes WHERE set_id = ? AND client_id = ?").get(req.params.id, clientOf(req));
  res.json(rowToPublic(row, liked));
});

/* POST /sets  (publish) */
app.post("/sets", writeLimiter, publishLimiter, (req, res) => {
  const body = req.body || {};
  const name = clean(body.name, MAX_NAME_LEN) || "Naamloos";
  const author = clean(body.author, MAX_AUTHOR_LEN) || "Anoniem";
  const lang = body.lang === "en" ? "en" : "nl";
  const code = clean(body.code, MAX_CODE_LEN);
  if (!code.startsWith("KGS1.")) return res.status(400).json({ error: "Invalid code" });

  // de-dup: same code already published? return it instead of a copy.
  const existing = db.prepare("SELECT * FROM sets WHERE code = ? AND hidden = 0").get(code);
  if (existing) return res.json(rowToPublic(existing, false));

  const id = newId();
  const createdAt = new Date().toISOString().slice(0, 10);
  db.prepare(
    "INSERT INTO sets (id, name, author, lang, code, created_at, client_id) VALUES (?, ?, ?, ?, ?, ?, ?)"
  ).run(id, name, author, lang, code, createdAt, clientOf(req));
  const row = db.prepare("SELECT * FROM sets WHERE id = ?").get(id);
  res.status(201).json(rowToPublic(row, false));
});

/* POST /sets/:id/like  (toggle, idempotent per client) */
app.post("/sets/:id/like", writeLimiter, (req, res) => {
  const id = req.params.id;
  const cid = clientOf(req);
  const set = db.prepare("SELECT * FROM sets WHERE id = ? AND hidden = 0").get(id);
  if (!set) return res.status(404).json({ error: "Not found" });
  const has = db.prepare("SELECT 1 FROM likes WHERE set_id = ? AND client_id = ?").get(id, cid);
  const tx = db.transaction(() => {
    if (has) {
      db.prepare("DELETE FROM likes WHERE set_id = ? AND client_id = ?").run(id, cid);
      db.prepare("UPDATE sets SET likes = MAX(0, likes - 1) WHERE id = ?").run(id);
    } else {
      db.prepare("INSERT OR IGNORE INTO likes (set_id, client_id) VALUES (?, ?)").run(id, cid);
      db.prepare("UPDATE sets SET likes = likes + 1 WHERE id = ?").run(id);
    }
  });
  tx();
  const likes = db.prepare("SELECT likes FROM sets WHERE id = ?").get(id).likes;
  res.json({ liked: !has, likes });
});

/* POST /sets/:id/use */
app.post("/sets/:id/use", writeLimiter, (req, res) => {
  const r = db.prepare("UPDATE sets SET uses = uses + 1 WHERE id = ? AND hidden = 0").run(req.params.id);
  if (r.changes === 0) return res.status(404).json({ error: "Not found" });
  const uses = db.prepare("SELECT uses FROM sets WHERE id = ?").get(req.params.id).uses;
  res.json({ uses });
});

/* POST /sets/:id/report  (auto-hide at a threshold) */
app.post("/sets/:id/report", writeLimiter, (req, res) => {
  const id = req.params.id;
  const cid = clientOf(req);
  const set = db.prepare("SELECT * FROM sets WHERE id = ?").get(id);
  if (!set) return res.status(404).json({ error: "Not found" });
  const inserted = db.prepare("INSERT OR IGNORE INTO reports (set_id, client_id) VALUES (?, ?)").run(id, cid);
  if (inserted.changes > 0) {
    db.prepare("UPDATE sets SET reports = reports + 1 WHERE id = ?").run(id);
    // auto-hide once 5 distinct clients report it; review manually in the db.
    db.prepare("UPDATE sets SET hidden = 1 WHERE id = ? AND reports >= 5").run(id);
  }
  res.json({ ok: true });
});

app.get("/ws-health", (_req, res) => res.json({ ok: true, ...roomEngine.stats() }));

app.use((_req, res) => res.status(404).json({ error: "Not found" }));

/* ---- WebSocket multiplayer on /ws ---- */
const httpServer = createServer(app);
const wss = new WebSocketServer({ server: httpServer, path: "/ws" });

function send(ws, msg) { try { ws.send(JSON.stringify(msg)); } catch { /* closed */ } }
function broadcast(room) {
  const state = roomEngine.publicState(room);
  for (const client of wss.clients) {
    if (client.readyState === 1 && client._code === room.code) {
      send(client, { t: "state", state });
    }
  }
}

wss.on("connection", (ws) => {
  ws._code = null;
  ws._pid = null;
  ws.on("message", (buf) => {
    let m;
    try { m = JSON.parse(String(buf)); } catch { return; }
    if (!m || typeof m.t !== "string") return;

    if (m.t === "create") {
      const room = roomEngine.create({
        hostId: m.playerId, name: m.name, setCode: m.setCode,
        setName: m.setName, lang: m.lang, alcoholFree: m.alcoholFree,
      });
      ws._code = room.code; ws._pid = m.playerId;
      send(ws, { t: "joined", code: room.code, playerId: m.playerId, hostId: room.hostId });
      broadcast(room);
      return;
    }
    if (m.t === "join") {
      const r = roomEngine.join({ code: m.code, playerId: m.playerId, name: m.name });
      if (r.error) { send(ws, { t: "error", error: r.error }); return; }
      ws._code = r.room.code; ws._pid = m.playerId;
      send(ws, { t: "joined", code: r.room.code, playerId: m.playerId, hostId: r.room.hostId });
      broadcast(r.room);
      return;
    }
    if (m.t === "action") {
      const r = roomEngine.action(ws._code, ws._pid, m.action, m.payload);
      if (r.error) { send(ws, { t: "error", error: r.error }); return; }
      if (r.room) broadcast(r.room);
      return;
    }
    if (m.t === "ping") { send(ws, { t: "pong" }); return; }
  });
  ws.on("close", () => {
    if (ws._code && ws._pid) {
      const room = roomEngine.disconnect(ws._code, ws._pid);
      if (room) broadcast(room);
    }
  });
});

// Host-grace watchdog: when a host's 10s grace expires, the room closes and we
// push the closed state to everyone still connected so they're notified.
setInterval(() => {
  try {
    const changed = roomEngine.tick();
    for (const room of changed) broadcast(room);
  } catch { /* ignore */ }
}, 1000).unref?.();

httpServer.listen(PORT, () => {
  console.log(`Kingsen server on :${PORT}  (engine: ${engine}, db: ${DB_PATH}, ws: /ws)`);
});
