/* ------------------------------------------------------------------ */
/*  Kingsen community-sets API                                          */
/*  Express + better-sqlite3. Single file, no build step.               */
/*                                                                      */
/*  Endpoints (all JSON):                                               */
/*    GET  /health                  -> { ok: true }                     */
/*    GET  /sets?q=&lang=&sort=      -> [ set, ... ]                     */
/*    GET  /sets/:id                 -> set                             */
/*    POST /sets                     -> set     (publish)               */
/*    POST /sets/:id/like            -> { liked, likes }                */
/*    POST /sets/:id/use             -> { uses }                        */
/*    POST /sets/:id/report          -> { ok }                          */
/*                                                                      */
/*  Client identity comes from the X-Client-Id header (anonymous,       */
/*  generated by the app). Used to make likes idempotent + rate-limit.  */
/* ------------------------------------------------------------------ */
import express from "express";
import cors from "cors";
import rateLimit from "express-rate-limit";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createServer } from "node:http";
import { WebSocketServer } from "ws";
import { createHmac } from "node:crypto";
import { openDatabase } from "./db.js";
import { roomEngine } from "./rooms.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const PORT = process.env.PORT || 8787;

/* ---- Voice (WebRTC audio) — self-hosted ICE: STUN + TURN via coturn on this host.
   The TURN secret stays server-side; we mint short-lived REST creds per client.
   TURN_HOST/SECRET/REALM are overridable via env (Coolify). ---- */
const TURN_HOST = process.env.TURN_HOST || "178.105.193.198";
const TURN_SECRET = process.env.TURN_SECRET || "kingsenTurn_7Qf3nZ8mWp2xR5vK9aJ4bL6";
const TURN_TTL = 12 * 60 * 60; // creds valid 12h
function iceServers() {
  const expiry = Math.floor(Date.now() / 1000) + TURN_TTL;
  const username = String(expiry);
  const credential = createHmac("sha1", TURN_SECRET).update(username).digest("base64");
  return [
    { urls: `stun:${TURN_HOST}:3478` },
    { urls: "stun:stun.l.google.com:19302" }, // public fallback
    { urls: [`turn:${TURN_HOST}:3478?transport=udp`, `turn:${TURN_HOST}:3478?transport=tcp`], username, credential },
  ];
}
const DB_PATH = process.env.KINGSEN_DB || join(__dirname, "kingsen.db");
// comma-separated allowlist, e.g. "https://kingsen.app,https://www.kingsen.app"
// default "*" is fine for a public read/write gallery, but lock down for prod.
const ORIGINS = (process.env.KINGSEN_ORIGINS || "*").split(",").map((s) => s.trim());

const MAX_CODE_LEN = 4000;   // a KGS1 code; generous but bounded
const MAX_NAME_LEN = 40;
const MAX_AUTHOR_LEN = 24;

/* ---- db (better-sqlite3 if present, else built-in node:sqlite) ---- */
const { db, engine } = await openDatabase(DB_PATH);
db.exec(`
  CREATE TABLE IF NOT EXISTS sets (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    author     TEXT NOT NULL,
    lang       TEXT NOT NULL DEFAULT 'nl',
    code       TEXT NOT NULL,
    uses       INTEGER NOT NULL DEFAULT 0,
    likes      INTEGER NOT NULL DEFAULT 0,
    reports    INTEGER NOT NULL DEFAULT 0,
    hidden     INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    client_id  TEXT
  );
  CREATE TABLE IF NOT EXISTS likes (
    set_id    TEXT NOT NULL,
    client_id TEXT NOT NULL,
    PRIMARY KEY (set_id, client_id)
  );
  CREATE TABLE IF NOT EXISTS reports (
    set_id    TEXT NOT NULL,
    client_id TEXT NOT NULL,
    PRIMARY KEY (set_id, client_id)
  );
  CREATE TABLE IF NOT EXISTS entitlements (
    code       TEXT PRIMARY KEY,
    decks      TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_sets_uses  ON sets (uses DESC);
  CREATE INDEX IF NOT EXISTS idx_sets_likes ON sets (likes DESC);
  CREATE INDEX IF NOT EXISTS idx_sets_new   ON sets (created_at DESC);
`);

// Auto-seed the example sets on first boot (empty table), unless disabled.
if (process.env.KINGSEN_NO_SEED !== "1") {
  try {
    const count = db.prepare("SELECT COUNT(*) AS n FROM sets").get().n;
    if (Number(count) === 0) {
      const { seedInto } = await import("./seedData.js");
      const n = seedInto(db);
      console.log(`Seeded ${n} example set(s) on first boot.`);
    }
  } catch (e) {
    console.warn("Auto-seed skipped:", e.message);
  }
}

/* ---- helpers ---- */
const newId = () => "s_" + Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4);
const clientOf = (req) => String(req.get("X-Client-Id") || req.ip || "anon").slice(0, 64);
function clean(str, max) {
  return String(str == null ? "" : str).replace(/[\u0000-\u001f\u007f]/g, "").trim().slice(0, max);
}
function rowToPublic(row, liked) {
  return {
    id: row.id, name: row.name, author: row.author, lang: row.lang,
    code: row.code, uses: row.uses, likes: row.likes,
    createdAt: row.created_at, liked: !!liked,
  };
}

/* ---- app ---- */
const app = express();
app.set("trust proxy", 1); // behind nginx/caddy
app.use(express.json({ limit: "128kb" })); // room create/join carry a small avatar data URL
app.use(cors({
  origin: ORIGINS.includes("*") ? true : ORIGINS,
  methods: ["GET", "POST"],
  allowedHeaders: ["Content-Type", "X-Client-Id"],
}));

const writeLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 20,                       // 20 writes/min per IP
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many requests, slow down." },
});
const publishLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 30,                       // 30 publishes/hour per IP
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Publish limit reached, try again later." },
});

app.get("/health", (_req, res) => res.json({ ok: true, engine }));

/* GET /sets */
app.get("/sets", (req, res) => {
  const sort = req.query.sort === "new" ? "created_at DESC"
    : req.query.sort === "likes" ? "likes DESC, uses DESC"
    : "uses DESC, likes DESC";
  const lang = clean(req.query.lang, 5);
  const q = clean(req.query.q, 60).toLowerCase();
  let sql = "SELECT * FROM sets WHERE hidden = 0";
  const params = [];
  if (lang === "nl" || lang === "en") { sql += " AND lang = ?"; params.push(lang); }
  if (q) { sql += " AND (lower(name) LIKE ? OR lower(author) LIKE ?)"; params.push("%" + q + "%", "%" + q + "%"); }
  sql += ` ORDER BY ${sort} LIMIT 100`;
  const rows = db.prepare(sql).all(...params);
  const cid = clientOf(req);
  const likedSet = new Set(
    db.prepare("SELECT set_id FROM likes WHERE client_id = ?").all(cid).map((r) => r.set_id)
  );
  res.json(rows.map((r) => rowToPublic(r, likedSet.has(r.id))));
});

/* GET /sets/:id */
app.get("/sets/:id", (req, res) => {
  const row = db.prepare("SELECT * FROM sets WHERE id = ? AND hidden = 0").get(req.params.id);
  if (!row) return res.status(404).json({ error: "Not found" });
  const liked = !!db.prepare("SELECT 1 FROM likes WHERE set_id = ? AND client_id = ?").get(req.params.id, clientOf(req));
  res.json(rowToPublic(row, liked));
});

/* POST /sets  (publish) */
app.post("/sets", writeLimiter, publishLimiter, (req, res) => {
  const body = req.body || {};
  const name = clean(body.name, MAX_NAME_LEN) || "Naamloos";
  const author = clean(body.author, MAX_AUTHOR_LEN) || "Anoniem";
  const lang = body.lang === "en" ? "en" : "nl";
  const code = clean(body.code, MAX_CODE_LEN);
  if (!code.startsWith("KGS1.")) return res.status(400).json({ error: "Invalid code" });

  // de-dup: same code already published? return it instead of a copy.
  const existing = db.prepare("SELECT * FROM sets WHERE code = ? AND hidden = 0").get(code);
  if (existing) return res.json(rowToPublic(existing, false));

  const id = newId();
  const createdAt = new Date().toISOString().slice(0, 10);
  db.prepare(
    "INSERT INTO sets (id, name, author, lang, code, created_at, client_id) VALUES (?, ?, ?, ?, ?, ?, ?)"
  ).run(id, name, author, lang, code, createdAt, clientOf(req));
  const row = db.prepare("SELECT * FROM sets WHERE id = ?").get(id);
  res.status(201).json(rowToPublic(row, false));
});

/* POST /sets/:id/like  (toggle, idempotent per client) */
app.post("/sets/:id/like", writeLimiter, (req, res) => {
  const id = req.params.id;
  const cid = clientOf(req);
  const set = db.prepare("SELECT * FROM sets WHERE id = ? AND hidden = 0").get(id);
  if (!set) return res.status(404).json({ error: "Not found" });
  const has = db.prepare("SELECT 1 FROM likes WHERE set_id = ? AND client_id = ?").get(id, cid);
  const tx = db.transaction(() => {
    if (has) {
      db.prepare("DELETE FROM likes WHERE set_id = ? AND client_id = ?").run(id, cid);
      db.prepare("UPDATE sets SET likes = MAX(0, likes - 1) WHERE id = ?").run(id);
    } else {
      db.prepare("INSERT OR IGNORE INTO likes (set_id, client_id) VALUES (?, ?)").run(id, cid);
      db.prepare("UPDATE sets SET likes = likes + 1 WHERE id = ?").run(id);
    }
  });
  tx();
  const likes = db.prepare("SELECT likes FROM sets WHERE id = ?").get(id).likes;
  res.json({ liked: !has, likes });
});

/* POST /sets/:id/use */
app.post("/sets/:id/use", writeLimiter, (req, res) => {
  const r = db.prepare("UPDATE sets SET uses = uses + 1 WHERE id = ? AND hidden = 0").run(req.params.id);
  if (r.changes === 0) return res.status(404).json({ error: "Not found" });
  const uses = db.prepare("SELECT uses FROM sets WHERE id = ?").get(req.params.id).uses;
  res.json({ uses });
});

/* POST /sets/:id/report  (auto-hide at a threshold) */
app.post("/sets/:id/report", writeLimiter, (req, res) => {
  const id = req.params.id;
  const cid = clientOf(req);
  const set = db.prepare("SELECT * FROM sets WHERE id = ?").get(id);
  if (!set) return res.status(404).json({ error: "Not found" });
  const inserted = db.prepare("INSERT OR IGNORE INTO reports (set_id, client_id) VALUES (?, ?)").run(id, cid);
  if (inserted.changes > 0) {
    db.prepare("UPDATE sets SET reports = reports + 1 WHERE id = ?").run(id);
    // auto-hide once 5 distinct clients report it; review manually in the db.
    db.prepare("UPDATE sets SET hidden = 1 WHERE id = ? AND reports >= 5").run(id);
  }
  res.json({ ok: true });
});

app.get("/ws-health", (_req, res) => res.json({ ok: true, ...roomEngine.stats() }));

/* ---- HTTP polling transport for online play (alternative to /ws) ----
   Same authoritative roomEngine as the WebSocket. A turn-based game doesn't need
   a persistent socket: the client POSTs actions and GETs the state every ~1.5s.
   There's no connection to go half-open, so it can't "miss the last broadcast"
   and freeze — every poll returns the current state. */
const rl = rateLimit({ windowMs: 60 * 1000, max: 600, standardHeaders: true, legacyHeaders: false, message: { error: "Slow down" } });

app.post("/api/room", rl, (req, res) => {
  const b = req.body || {};
  if (!b.playerId) return res.status(400).json({ error: "Missing playerId" });
  const room = roomEngine.create({ hostId: b.playerId, name: b.name, setCode: b.setCode, setName: b.setName, lang: b.lang, alcoholFree: b.alcoholFree, avatar: b.avatar });
  roomEngine.touch(room.code, b.playerId);
  res.json({ code: room.code, hostId: room.hostId, playerId: b.playerId, state: roomEngine.publicState(room) });
});

app.post("/api/room/:code/join", rl, (req, res) => {
  const b = req.body || {};
  if (!b.playerId) return res.status(400).json({ error: "Missing playerId" });
  const r = roomEngine.join({ code: req.params.code, playerId: b.playerId, name: b.name, avatar: b.avatar });
  if (r.error) return res.status(409).json({ error: r.error });
  roomEngine.touch(r.room.code, b.playerId);
  res.json({ code: r.room.code, hostId: r.room.hostId, playerId: b.playerId, state: roomEngine.publicState(r.room) });
});

app.get("/api/room/:code", rl, (req, res) => {
  const pid = req.query.pid ? String(req.query.pid) : null;
  const room = pid ? roomEngine.touch(req.params.code, pid) : roomEngine.get(req.params.code);
  if (!room) return res.status(404).json({ error: "Room niet gevonden" });
  res.json({ code: room.code, hostId: room.hostId, state: roomEngine.publicState(room) });
});

app.post("/api/room/:code/action", rl, (req, res) => {
  const b = req.body || {};
  if (!b.playerId) return res.status(400).json({ error: "Missing playerId" });
  roomEngine.touch(req.params.code, b.playerId);
  const r = roomEngine.action(req.params.code, b.playerId, b.action, b.payload);
  if (r.error) return res.status(409).json({ error: r.error });
  res.json({ code: r.room.code, hostId: r.room.hostId, state: roomEngine.publicState(r.room) });
});

// ---- Entitlements (owned premium decks) keyed by a portable RESTORE CODE ----
// No accounts / no PII: the code IS the credential. Lets purchases survive a
// reinstall + move across devices. NOTE: there's no real payment yet, so the
// client writes its (test-)unlocked decks here; once a payment provider exists
// the GRANT must move server-side (webhook) and the client should only READ.
function makeRestoreCode() {
  const A = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // unambiguous (no O/0/I/1)
  let c = ""; for (let i = 0; i < 10; i++) c += A[Math.floor(Math.random() * A.length)];
  return c;
}
app.post("/api/entitlements", rl, (req, res) => {
  const b = req.body || {};
  const decks = Array.isArray(b.decks) ? b.decks.filter((d) => typeof d === "string").slice(0, 50) : [];
  let code = (typeof b.code === "string" && /^[A-Z2-9]{10}$/.test(b.code.toUpperCase())) ? b.code.toUpperCase() : null;
  const now = new Date().toISOString();
  if (!code) { do { code = makeRestoreCode(); } while (db.prepare("SELECT 1 FROM entitlements WHERE code = ?").get(code)); }
  if (db.prepare("SELECT 1 FROM entitlements WHERE code = ?").get(code))
    db.prepare("UPDATE entitlements SET decks = ?, updated_at = ? WHERE code = ?").run(JSON.stringify(decks), now, code);
  else
    db.prepare("INSERT INTO entitlements (code, decks, created_at, updated_at) VALUES (?,?,?,?)").run(code, JSON.stringify(decks), now, now);
  res.json({ code, decks });
});
app.get("/api/entitlements/:code", rl, (req, res) => {
  const code = String(req.params.code || "").toUpperCase();
  const row = db.prepare("SELECT decks FROM entitlements WHERE code = ?").get(code);
  if (!row) return res.status(404).json({ error: "Code niet gevonden" });
  let decks = []; try { decks = JSON.parse(row.decks); } catch { /* */ }
  res.json({ code, decks });
});

app.use((_req, res) => res.status(404).json({ error: "Not found" }));

/* ---- WebSocket multiplayer on /ws ---- */
const httpServer = createServer(app);
const wss = new WebSocketServer({ server: httpServer, path: "/ws" });

function send(ws, msg) { try { ws.send(JSON.stringify(msg)); } catch { /* closed */ } }
function broadcast(room) {
  const state = roomEngine.publicState(room);
  for (const client of wss.clients) {
    if (client.readyState === 1 && client._code === room.code) {
      send(client, { t: "state", state });
    }
  }
}
// A reconnect (heartbeat re-join from the same player) leaves the OLD socket
// behind. Drop it so there's exactly one live socket per player — otherwise the
// dead socket's late close marks the player offline AFTER they reconnected (and
// would re-arm the host-away grace, closing a room whose host is actually here).
function supersedeOldSockets(ws) {
  for (const c of wss.clients) {
    if (c !== ws && c._code === ws._code && c._pid === ws._pid) {
      c._superseded = true;
      try { c.terminate(); } catch { /* */ }
    }
  }
}
// Is another live socket already serving this player in this room?
function hasLiveSibling(ws) {
  for (const c of wss.clients) {
    if (c !== ws && c.readyState === 1 && c._code === ws._code && c._pid === ws._pid) return true;
  }
  return false;
}

// Relay a voice message to every OTHER voice socket in the same room.
function voiceBroadcast(code, msg, except) {
  for (const c of wss.clients) {
    if (c !== except && c.readyState === 1 && c._vcode === code && c._vpid) send(c, msg);
  }
}

wss.on("connection", (ws) => {
  ws._code = null;
  ws._pid = null;
  ws._vcode = null;   // voice room (separate from the game socket identity)
  ws._vpid = null;
  ws.on("message", (buf) => {
    let m;
    try { m = JSON.parse(String(buf)); } catch { return; }
    if (!m || typeof m.t !== "string") return;

    /* ---- Voice (WebRTC audio) signaling — rides on /ws, independent of game state ---- */
    if (m.t === "voice-join") {
      ws._vcode = String(m.code || "").toUpperCase(); ws._vpid = String(m.pid || "");
      if (!ws._vcode || !ws._vpid) return;
      const peers = [];
      for (const c of wss.clients) if (c !== ws && c.readyState === 1 && c._vcode === ws._vcode && c._vpid) peers.push(c._vpid);
      send(ws, { t: "voice-welcome", peers, iceServers: iceServers() });
      voiceBroadcast(ws._vcode, { t: "voice-peer", pid: ws._vpid }, ws); // tell existing peers a newcomer arrived
      return;
    }
    if (m.t === "voice-signal") {                 // relay an SDP offer/answer or ICE candidate to one peer
      if (!ws._vcode || !ws._vpid) return;
      for (const c of wss.clients) {
        if (c.readyState === 1 && c._vcode === ws._vcode && c._vpid === m.to) { send(c, { t: "voice-signal", from: ws._vpid, data: m.data }); break; }
      }
      return;
    }
    if (m.t === "voice-leave") {
      const code = ws._vcode, pid = ws._vpid; ws._vcode = null; ws._vpid = null;
      if (code && pid) voiceBroadcast(code, { t: "voice-bye", pid }, ws);
      return;
    }

    if (m.t === "create") {
      const room = roomEngine.create({
        hostId: m.playerId, name: m.name, setCode: m.setCode,
        setName: m.setName, lang: m.lang, alcoholFree: m.alcoholFree, avatar: m.avatar,
      });
      ws._code = room.code; ws._pid = m.playerId;
      supersedeOldSockets(ws);
      send(ws, { t: "joined", code: room.code, playerId: m.playerId, hostId: room.hostId });
      broadcast(room);
      return;
    }
    if (m.t === "join") {
      const r = roomEngine.join({ code: m.code, playerId: m.playerId, name: m.name, avatar: m.avatar });
      if (r.error) { send(ws, { t: "error", error: r.error }); return; }
      ws._code = r.room.code; ws._pid = m.playerId;
      supersedeOldSockets(ws);
      send(ws, { t: "joined", code: r.room.code, playerId: m.playerId, hostId: r.room.hostId });
      broadcast(r.room);
      return;
    }
    if (m.t === "action") {
      const r = roomEngine.action(ws._code, ws._pid, m.action, m.payload);
      if (r.error) { send(ws, { t: "error", error: r.error }); return; }
      if (r.room) broadcast(r.room);
      return;
    }
    if (m.t === "ping") { send(ws, { t: "pong" }); return; }
  });
  ws.on("close", () => {
    if (ws._vcode && ws._vpid) { voiceBroadcast(ws._vcode, { t: "voice-bye", pid: ws._vpid }, ws); ws._vcode = null; ws._vpid = null; }
    if (!ws._code || !ws._pid) return;
    // Reconnect-race guard: if a newer live socket already serves this player
    // (they reconnected), this socket was superseded — its close must NOT mark
    // the player offline or re-arm the host-away grace, or a present host's room
    // would wrongly close ~10s later. Only the player's LAST socket disconnects.
    if (ws._superseded || hasLiveSibling(ws)) return;
    const room = roomEngine.disconnect(ws._code, ws._pid);
    if (room) broadcast(room);
  });
});

// Host-grace watchdog: when a host's 10s grace expires, the room closes and we
// push the closed state to everyone still connected so they're notified.
setInterval(() => {
  try {
    const changed = roomEngine.tick();
    for (const room of changed) broadcast(room);
  } catch { /* ignore */ }
}, 1000).unref?.();

httpServer.listen(PORT, () => {
  console.log(`Kingsen server on :${PORT}  (engine: ${engine}, db: ${DB_PATH}, ws: /ws)`);
});
